/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protocol.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "protocol.pb-c.h"
void   protocol__frame__init
                     (Protocol__Frame         *message)
{
  static const Protocol__Frame init_value = PROTOCOL__FRAME__INIT;
  *message = init_value;
}
size_t protocol__frame__get_packed_size
                     (const Protocol__Frame *message)
{
  assert(message->base.descriptor == &protocol__frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__frame__pack
                     (const Protocol__Frame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &protocol__frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__frame__pack_to_buffer
                     (const Protocol__Frame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &protocol__frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__Frame *
       protocol__frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__Frame *)
     protobuf_c_message_unpack (&protocol__frame__descriptor,
                                allocator, len, data);
}
void   protocol__frame__free_unpacked
                     (Protocol__Frame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &protocol__frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor protocol__frame__field_descriptors[5] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Protocol__Frame, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Protocol__Frame, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "distance",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Protocol__Frame, distance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ID",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Protocol__Frame, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "color",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Protocol__Frame, color),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__frame__field_indices_by_name[] = {
  3,   /* field[3] = ID */
  4,   /* field[4] = color */
  2,   /* field[2] = distance */
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange protocol__frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor protocol__frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Protocol.Frame",
  "Frame",
  "Protocol__Frame",
  "Protocol",
  sizeof(Protocol__Frame),
  5,
  protocol__frame__field_descriptors,
  protocol__frame__field_indices_by_name,
  1,  protocol__frame__number_ranges,
  (ProtobufCMessageInit) protocol__frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
