/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protocol.proto */

#ifndef PROTOBUF_C_protocol_2eproto__INCLUDED
#define PROTOBUF_C_protocol_2eproto__INCLUDED

#include <protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Protocol__Frame Protocol__Frame;


/* --- enums --- */


/* --- messages --- */

struct  _Protocol__Frame
{
  ProtobufCMessage base;
  int32_t x;
  int32_t y;
  int32_t distance;
  int32_t id;
  int32_t color;
};
#define PROTOCOL__FRAME__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__frame__descriptor) \
    , 0, 0, 0, 0, 0 }


/* Protocol__Frame methods */
void   protocol__frame__init
                     (Protocol__Frame         *message);
size_t protocol__frame__get_packed_size
                     (const Protocol__Frame   *message);
size_t protocol__frame__pack
                     (const Protocol__Frame   *message,
                      uint8_t             *out);
size_t protocol__frame__pack_to_buffer
                     (const Protocol__Frame   *message,
                      ProtobufCBuffer     *buffer);
Protocol__Frame *
       protocol__frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protocol__frame__free_unpacked
                     (Protocol__Frame *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Protocol__Frame_Closure)
                 (const Protocol__Frame *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor protocol__frame__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_protocol_2eproto__INCLUDED */
