/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: recieve_sentry.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "recieve_sentry.pb-c.h"
void   e_to_v__frame__init
                     (EToV__Frame         *message)
{
  static const EToV__Frame init_value = E_TO_V__FRAME__INIT;
  *message = init_value;
}
size_t e_to_v__frame__get_packed_size
                     (const EToV__Frame *message)
{
  assert(message->base.descriptor == &e_to_v__frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t e_to_v__frame__pack
                     (const EToV__Frame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &e_to_v__frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t e_to_v__frame__pack_to_buffer
                     (const EToV__Frame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &e_to_v__frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EToV__Frame *
       e_to_v__frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EToV__Frame *)
     protobuf_c_message_unpack (&e_to_v__frame__descriptor,
                                allocator, len, data);
}
void   e_to_v__frame__free_unpacked
                     (EToV__Frame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &e_to_v__frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor e_to_v__frame__field_descriptors[13] =
{
  {
    "currentPitch_",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EToV__Frame, currentpitch_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "currentYaw_",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EToV__Frame, currentyaw_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "currentColor_",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EToV__Frame, currentcolor_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bulletSpeed_",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EToV__Frame, bulletspeed_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "booldVol_",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EToV__Frame, booldvol_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode_",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EToV__Frame, mode_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "guard_",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EToV__Frame, guard_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hero_",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EToV__Frame, hero_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "engineer_",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EToV__Frame, engineer_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "infantry3_",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EToV__Frame, infantry3_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "infantry4_",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EToV__Frame, infantry4_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "infantry5_",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EToV__Frame, infantry5_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "base_",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(EToV__Frame, base_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned e_to_v__frame__field_indices_by_name[] = {
  12,   /* field[12] = base_ */
  4,   /* field[4] = booldVol_ */
  3,   /* field[3] = bulletSpeed_ */
  2,   /* field[2] = currentColor_ */
  0,   /* field[0] = currentPitch_ */
  1,   /* field[1] = currentYaw_ */
  8,   /* field[8] = engineer_ */
  6,   /* field[6] = guard_ */
  7,   /* field[7] = hero_ */
  9,   /* field[9] = infantry3_ */
  10,   /* field[10] = infantry4_ */
  11,   /* field[11] = infantry5_ */
  5,   /* field[5] = mode_ */
};
static const ProtobufCIntRange e_to_v__frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor e_to_v__frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "e_to_v.Frame",
  "Frame",
  "EToV__Frame",
  "e_to_v",
  sizeof(EToV__Frame),
  13,
  e_to_v__frame__field_descriptors,
  e_to_v__frame__field_indices_by_name,
  1,  e_to_v__frame__number_ranges,
  (ProtobufCMessageInit) e_to_v__frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
