/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: send.proto */

#ifndef PROTOBUF_C_send_2eproto__INCLUDED
#define PROTOBUF_C_send_2eproto__INCLUDED

#include <protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _VToE__Frame VToE__Frame;


/* --- enums --- */


/* --- messages --- */

struct  _VToE__Frame
{
  ProtobufCMessage base;
  float targetpitch_;
  float targetyaw_;
  int32_t x_;
  int32_t y_;
};
#define V_TO_E__FRAME__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&v_to_e__frame__descriptor) \
    , 0, 0, 0, 0 }


/* VToE__Frame methods */
void   v_to_e__frame__init
                     (VToE__Frame         *message);
size_t v_to_e__frame__get_packed_size
                     (const VToE__Frame   *message);
size_t v_to_e__frame__pack
                     (const VToE__Frame   *message,
                      uint8_t             *out);
size_t v_to_e__frame__pack_to_buffer
                     (const VToE__Frame   *message,
                      ProtobufCBuffer     *buffer);
VToE__Frame *
       v_to_e__frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   v_to_e__frame__free_unpacked
                     (VToE__Frame *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*VToE__Frame_Closure)
                 (const VToE__Frame *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor v_to_e__frame__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_send_2eproto__INCLUDED */
