/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: send.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "send.pb-c.h"
void   v_to_e__frame__init
                     (VToE__Frame         *message)
{
  static const VToE__Frame init_value = V_TO_E__FRAME__INIT;
  *message = init_value;
}
size_t v_to_e__frame__get_packed_size
                     (const VToE__Frame *message)
{
  assert(message->base.descriptor == &v_to_e__frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t v_to_e__frame__pack
                     (const VToE__Frame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &v_to_e__frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t v_to_e__frame__pack_to_buffer
                     (const VToE__Frame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &v_to_e__frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VToE__Frame *
       v_to_e__frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VToE__Frame *)
     protobuf_c_message_unpack (&v_to_e__frame__descriptor,
                                allocator, len, data);
}
void   v_to_e__frame__free_unpacked
                     (VToE__Frame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &v_to_e__frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor v_to_e__frame__field_descriptors[4] =
{
  {
    "targetPitch_",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(VToE__Frame, targetpitch_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "targetYaw_",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(VToE__Frame, targetyaw_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x_",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(VToE__Frame, x_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y_",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(VToE__Frame, y_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned v_to_e__frame__field_indices_by_name[] = {
  0,   /* field[0] = targetPitch_ */
  1,   /* field[1] = targetYaw_ */
  2,   /* field[2] = x_ */
  3,   /* field[3] = y_ */
};
static const ProtobufCIntRange v_to_e__frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor v_to_e__frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "v_to_e.Frame",
  "Frame",
  "VToE__Frame",
  "v_to_e",
  sizeof(VToE__Frame),
  4,
  v_to_e__frame__field_descriptors,
  v_to_e__frame__field_indices_by_name,
  1,  v_to_e__frame__number_ranges,
  (ProtobufCMessageInit) v_to_e__frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
